spring:
  application:
    name: spring-boot-micrometer-datadog-quickstart
  main:
    allow-bean-definition-overriding: true

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.95, 0.99      
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 200ms, 400ms, 600ms
    export:
      datadog:
        api-key: foo
        application-key: bar
        step: 30s
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles}